# Generated by Django 4.1.13 on 2024-05-06 16:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_purchaseorder_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='items',
            field=models.JSONField(validators=[api.models.validate_items]),
        ),
    ]
